Update config

diff --git a/.github/workflows/pure-padavanonly-360t7-24.10-6.6.yml b/.github/workflows/pure-padavanonly-360t7-24.10-6.6.yml
--- a/.github/workflows/pure-padavanonly-360t7-24.10-6.6.yml
+++ b/.github/workflows/pure-padavanonly-360t7-24.10-6.6.yml
@@ -12,7 +12,7 @@ env:
   REPO_URL: https://github.com/padavanonly/immortalwrt-mt798x-24.10
   REPO_BRANCH: openwrt-24.10-6.6
   FEEDS_CONF: feeds.conf.default
-  CONFIG_FILE: pure.config
+  CONFIG_FILE: pure237.config
   DIY_P1_SH: diy-part1.sh
   DIY_P2_SH: diy-part2.sh
   UPLOAD_FIRMWARE: true
@@ -105,6 +105,12 @@ jobs:
       id: compile
       run: |
         cd openwrt
+        sed -i 's/192.168.6.1/192.168.123.1/g' package/base-files/files/bin/config_generate
+        sed -i 's/PKG_VERSION:=1.89.0/PKG_VERSION:=1.92.0/g' feeds/packages/lang/rust/Makefile
+        sed -i 's/PKG_HASH:=0b9d55610d8270e06c44f459d1e2b7918a5e673809c592abed9b9c600e33d95a/PKG_HASH:=ebee170bfe4c4dfc59521a101de651e5534f4dae889756a5c97ca9ea40d0c307/g' feeds/packages/lang/rust/Makefile
+        sed -i 's/PKG_BUILD_FLAGS:=no-mips16/PKG_USE_MIPS16:=0/g' feeds/packages/lang/rust/Makefile
+        sed -i '86i\define Host/Patch\n\t$(if $(HOST_QUILT),rm -rf $(HOST_BUILD_DIR)/patches; mkdir -p $(HOST_BUILD_DIR)/patches)\n\t$(if $(HOST_QUILT),$(call PatchDir/Quilt,$(HOST_BUILD_DIR),$(HOST_PATCH_DIR),))\n\t$(if $(HOST_QUILT),touch $(HOST_BUILD_DIR)/.quilt_used)\n\t$(if $(HOST_QUILT),,$(if $(wildcard $(HOST_PATCH_DIR)/*.patch), \\\n\t\t$(foreach p,$(sort $(wildcard $(HOST_PATCH_DIR)/*.patch)), \\\n\t\t\techo "Applying patch $(notdir $p)" ; \\\n\t\t\t$(PATCH) -f -p1 -d $(HOST_BUILD_DIR) < $p || \\\n\t\t\t{ echo "Patch failed! Please fix: $(notdir $p)!" ; exit 1 ; } ; \\\n\t\t) \\\n\t))\nendef' feeds/packages/lang/rust/Makefile
+        
         echo -e "$(nproc) thread compile"
         make -j$(nproc) || make -j1 || make -j1 V=s || (curl -k -d "title=OpenWrt-360T7固件编译失败" -d "content=编译固件版本：${{ env.FIRMWARE_VERSION }}%0A编译开始时间：${{ env.START_DATE }}%0A编译结束时间：$(date +'%Y年%m月%d日 %H点%M分%S秒')" -d "token=${{ env.PUSHPLUS_TOKEN }}&channel=cp&webhook=server" "http://www.pushplus.plus/send")
         echo "status=success" >> $GITHUB_OUTPUT
@@ -123,8 +129,8 @@ jobs:
         rm -rf *kernel*
         rm -rf *.manifest
         rm -rf sha256sums
-        mv *sysupgrade.bin ${{ env.FIRMWARE_VERSION }}-ImmortalWrt-360T7-108M-sysupgrade.bin
-        mv *factory.bin ${{ env.FIRMWARE_VERSION }}-ImmortalWrt-360T7-108M-factory.bin
+        mv *sysupgrade.bin ${{ env.FIRMWARE_VERSION }}-ImmortalWrt-360T7-sysupgrade.bin
+        mv *factory.bin ${{ env.FIRMWARE_VERSION }}-ImmortalWrt-360T7-factory.bin
         echo "FIRMWARE=$PWD" >> $GITHUB_ENV
         echo "status=success" >> $GITHUB_OUTPUT
         
